name: 🏷️ Deploy VitePress Docs

on:
  push:
    tags:
      - 'v*' # Only trigger when a version tag is pushed, like v1.0.0
  workflow_dispatch:

jobs:
  deploy-vitePress:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for GitHub Packages

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Set up Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: 📝 Build the documentation
        run: pnpm run docs && pnpm run docs:build

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist
          branch: docs
          token: ${{ secrets.GITHUB_TOKEN }}
